# Generated by Django 5.2.17 on 2026-09-22 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='nombre',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='rol',
            field=models.CharField(choices=[('personal', 'Personal'), ('cliente', 'Cliente'), ('jefe', 'Jefe')], default='cliente', max_length=10, verbose_name='tipo'),
        ),
    ]
