# Generated by Django 5.2.17 on 2026-09-21 13:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('rut', models.CharField(blank=True, max_length=12)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Archivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_original', models.CharField(max_length=255)),
                ('clave_space', models.CharField(max_length=512, unique=True)),
                ('tamano', models.PositiveBigIntegerField(verbose_name='tamaño (bytes)')),
                ('tipo', models.CharField(max_length=100)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('disponible', 'Disponible')], default='pendiente', max_length=10)),
                ('subido_en', models.DateTimeField(auto_now_add=True)),
                ('eliminado_en', models.DateTimeField(blank=True, null=True)),
                ('eliminado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archivos_eliminados', to=settings.AUTH_USER_MODEL)),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archivos_subidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-subido_en'],
            },
        ),
        migrations.CreateModel(
            name='DescargaLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('archivo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descargas', to='documentos.archivo')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='descargas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'descarga',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('cerrado', 'Cerrado')], default='activo', max_length=10)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proyectos', to='documentos.empresa')),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.AddField(
            model_name='archivo',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='archivos', to='documentos.proyecto'),
        ),
        migrations.CreateModel(
            name='Membresia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='membresias', to='documentos.proyecto')),
            ],
            options={
                'verbose_name': 'asignación',
                'verbose_name_plural': 'asignaciones de clientes',
                'unique_together': {('usuario', 'proyecto')},
            },
        ),
    ]
