# Generated by Django 5.2.17 on 2026-09-22 19:10

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RespuestaRecepcion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre_revisor', models.CharField(max_length=200)),
                ('conforme', models.BooleanField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas_recepcion', to='documentos.proyecto')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='respuestas_recepcion', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'respuesta de recepción',
                'verbose_name_plural': 'respuestas de recepción',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Hito',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('orden', models.PositiveSmallIntegerField()),
                ('nombre', models.CharField(max_length=200)),
                ('cumplido_en', models.DateTimeField(blank=True, null=True)),
                ('cumplido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hitos_cumplidos', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hitos', to='documentos.proyecto')),
            ],
            options={
                'verbose_name': 'hito',
                'verbose_name_plural': 'hitos',
                'ordering': ['orden'],
                'unique_together': {('proyecto', 'orden')},
            },
        ),
    ]
