# Generated by Django 5.2.17 on 2026-09-24 04:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_respuestarecepcion_hito'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carpeta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='carpetas_creadas', to=settings.AUTH_USER_MODEL)),
                ('proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carpetas', to='documentos.proyecto')),
            ],
            options={
                'verbose_name': 'carpeta',
                'verbose_name_plural': 'carpetas',
                'ordering': ['nombre'],
                'unique_together': {('proyecto', 'nombre')},
            },
        ),
        migrations.AddField(
            model_name='archivo',
            name='carpeta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos', to='documentos.carpeta'),
        ),
    ]
