# Generated by Django 5.2.17 on 2026-09-29 15:44

import datetime
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_encargados'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RechazoRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motivo', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'rechazo de la Revisión',
                'verbose_name_plural': 'rechazos de la Revisión',
                'ordering': ['-fecha'],
            },
        ),
        migrations.AddField(
            model_name='hito',
            name='es_revision',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_inicio',
            field=models.DateField(default=datetime.date(2026, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='fecha_termino',
            field=models.DateField(default=datetime.date(2026, 1, 1)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proyecto',
            name='finalizado_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='hito',
            constraint=models.UniqueConstraint(condition=models.Q(('es_revision', True)), fields=('proyecto',), name='una_revision_por_proyecto'),
        ),
        migrations.AddField(
            model_name='rechazorevision',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rechazos_revision', to='documentos.proyecto'),
        ),
        migrations.AddField(
            model_name='rechazorevision',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rechazos_revision', to=settings.AUTH_USER_MODEL),
        ),
    ]
